= traQ bot 開発環境の構築方法 (外部開発者向け)

本記事では、外部の開発者が traQ bot を開発するための traQ の環境整備について説明します。

以下は全て手元環境にて行うことを想定し、他ユーザーが直接アクセスできない環境で行うことを想定します。

NOTE: 本稿は 2022年4月時点の内容であり、無保証です。また、筆者は traQ の開発者とは無関係です。

== 準備

手元環境に以下を導入してください。

* Docker
* Node.js v16
* yarn

== traQ

* traQ

https://github.com/traPtitch/traQ から traQ をダウンロードします。

....
$ git clone --filter=blob:none https://github.com/traPtitech/traQ
$ pushd traQ
....

....
$ make update-frontend
$ make up
....

`http://localhost:3000` にアクセスするとユーザー名 traq, パスワード traq にてログインできます。

== traQ bot console の traQ クライアントへの追加

traQ bot console 自体を 先ほど立てた traQ のクライアントとして追加する作業を行います。

まずは login してセッショントークン `cookie.txt` を取得します。

[source,json]
.login.json
----
{
   "name" : "traq",
   "password" : "traq"
}
----

....
$ curl -v -c cookie.txt -d @login.json -H "Content-Type: application/json" http://localhost:3000/api/v3/login
....

HTTP Status Code 204 が返れば成功です。以下では得られた session token が格納された cookie.txt を利用します。

次に traq bot console をクライアントとして登録します。
まずは、以下の内容で `oauth2.json` を作成します。
[source,json]
.oauth2.json
----
{
   "name" : "traqbotconsole",
   "scopes": [
	"manage_bot"
  ],
  "description": "traQ bot console",
  "callbackUrl" : "http://localhost:8080/callback"
}
----

....
curl -b cookie.txt -v -d @oauth2.json -H "Content-Type: application/json" http://localhost:3000/api/v3/clients
....

レスポンス中の `id` を控えます。

== traQ bot console

次に、bot 管理システムを導入します。

https://github.com/traPtitech/traQ-bot-console.git

....
$ git clone --filter=blob:none https://github.com/traPtitech/traQ-bot-console
$ pushd traQ-bot-console
....

`.env` に次のように記します。この際、 `id` は先ほどのレスポンスの通りにします。

.env
----
VUE_APP_API_ENDPOINT="http://localhost:3000/api/v3"
VUE_APP_API_CLIENT_ID="id"
----

`yarn` 及び `yarn run serve` を実行し、 traQ bot console が起動すれば成功です。

これ以降の Bot 開発作業は BOT Console から行えます。
